version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "tetri"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
